routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//route for product
Route::resource('product', 'product\productController');
//route for category
Route::resource('category', 'category\categoryController');
//route for brand
Route::resource('brand', 'brand\brandController');
//route for setting
Route::resource('setting', 'setting\settingController');
//route for advertisement
Route::resource('advertisement', 'advertisement\advertisementController');

//route for password change
Route::resource('changepassword', 'Auth\adminController');

//route of order
Route::GET('Order','product\ProductController@order')->name('order');

routes/user.php
<?php
Route::get('/', 'product\frontProductController@home')->name('main');
Route::GET('login','User\LoginController@showLoginForm')->name('user.login');
Route::GET('userlogout','User\LoginController@logout')->name('user.logout');
Route::POST('login','User\LoginController@login');
/*cart list */
Route::GET('my-cart/{id}','product\frontProductController@cartView')->name('cart');
Route::GET('cartdelete/{id}','product\frontProductController@cartDelete')->name('deletecart');
Route::POST('AddCart','product\frontProductController@addToCart')->name('addcart');
/*Wish list */
Route::POST('AddWish','product\frontProductController@addToWish')->name('addwishlist');
Route::GET('my-wish/{id}','product\frontProductController@wishView')->name('wish');
Route::GET('wishdelete/{id}','product\frontProductController@wishDelete')->name('deletewish');
/*product list */
Route::GET('listproduct','product\frontProductController@showListProduct')->name('listproduct');
Route::GET('productdetail/{slug}','product\frontProductController@showProductDetail')->name('listdetail');
/*brand */
Route::GET('Brand/{slug}','product\frontProductController@showListProductByBrand')->name('brand');
/*category */
Route::GET('Category/{slug}','product\frontProductController@showListProductByCategory')->name('category');

Route::POST('Search/Product','product\frontProductController@showSearchProduct')->name('search');
Route::GET('User/Help','product\frontProductController@showHelp')->name('help');
/*social login */
Route::get('auth/{provider}', 'User\LoginController@redirectToProvider');
Route::get('auth/{provider}/callback', 'User\LoginController@handleProviderCallback');
/*Pages */
Route::GET('Contact','product\frontProductController@showContact')->name('contact');
Route::GET('About','product\frontProductController@showAbout')->name('about');
/*Profile*/
Route::GET('My-Profile','User\userController@showProfile')->name('profile');
Route::GET('My-Profile/Edit-Profile','User\userController@showProfileEdit')->name('editprofile');
Route::GET('My-Profile/Change-Password','User\userController@showpassword')->name('password');
Route::POST('changepassword/{id}','User\userController@changepassword')->name('changepassword');
Route::POST('changeprofile/{id}','User\userController@update')->name('profileedit');

Route::POST('registeruser','User\userController@userRegister')->name('userregister');
?>

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('index', 'HomeController@home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/advertisement/advertisementController.php
<?php 
namespace App\Http\Controllers\advertisement;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repo\Repository\Advertisement\AdvertisementRepositoryInterface;

class advertisementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct(AdvertisementRepositoryInterface $advertisement)
    {
        $this->advertisement=$advertisement;
    }
    public function index()
    {
        $advertisement = $this->advertisement->index();
       return view('layouts/admin/pages/advertisement/advertisement',compact('advertisement'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('layouts/admin/pages/advertisement/addadvertisement');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
            if($request->hasFile('img'))
            {
                
                $imgName = time().'-'.$request->file('img')->getClientOriginalName();
                $path = 'public/images/advertisement/';
                $request->file('img')->move($path,$imgName);
                $advdetails['image']=$imgName;
            }
        $advdetails['name']=$request->name;
        $advdetails['description']=$request->description;
        $adv=$this->advertisement->create($advdetails);
        return redirect()->route('advertisement.index')->with('success', 'Your Advertisement has been successfully Added.');
        }
        catch(\Exception $e){
            dd($e);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $editadvertisement=$this->advertisement->find($id);
        return view('layouts.admin.pages.advertisement.editadvertisement',compact('editadvertisement'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try{

            if($request->hasFile('img'))
        {
            //deleting image
            $advertisement=$this->advertisement->find($id);
            unlink(public_path()."/images/advertisement/".$advertisement->image);
            $imgName = time().'-'.$request->file('img')->getClientOriginalName();
            $path = 'public/images/advertisement/';
            $request->file('img')->move($path,$imgName);
            $advertisementdetails['image']=$imgName;
            }
        $advertisementdetails['name']=$request->name;
        $advertisementdetails['description']=$request->description;
        $user=$this->advertisement->update($id,$advertisementdetails);
        return redirect()->route('advertisement.index')->with('success', 'Your advertisement has been successfully Updated.');
        }
        catch(Exception $e){
            dd($e);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
          $advertisement=$this->advertisement->find($id);
        // dd($event);
        if(!$advertisement->image == ""){
        unlink(public_path()."/images/advertisement/".$advertisement->image);
    }
        $this->advertisement->delete($id);
        return redirect()->route('advertisement.index')->with('error', 'Your Advertisement has been successfully deleted.');
    }
}

resources/views/layouts/admin/pages/advertisement/addadvertisement.blade.php
@extends('layouts.app')

@section('content')

<div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item active"><a href="{{route('home')}}"><span class="nav-link-text">Dashboard</span></a> / <a href="{{route('advertisement.index')}}"><span class="nav-link-text">Advertisments</span></a> / Add Advertisment</li>
      </ol>      
          <div class="row">
            <div class="col-lg-12">
              <form role="form" method="post" action="{{route('advertisement.store')}}" enctype="multipart/form-data">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <div class="row p-3">
                <div class="col-lg-6">
                <div class="form-group">
                <label>Advertisment Name</label>

                <input class="form-control" name="name" placeholder="Enter Advertisment Name">
                </div>
              </div>
              <div class="col-lg-12">
                <div class="form-group">
                <label>Description</label>
                <textarea class="form-control" name="description" placeholder="Enter Advertisment Description" rows="3"></textarea>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="form-group">
                <label>Product Image (PNG,JPG) : </label>
                <input type="file" name="img">
                </div>
              </div>
              <div class="col-lg-12">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{{ route('advertisement.index') }}" class="btn btn-danger">Cancel</a>
                </div>
              </div>              
              </form>
              </div>
          </div>
    </div>
  </div>
    
@endsection

resources/views/layouts/admin/pages/advertisement/advertisement.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item active"><a href="{{route('home')}}"><span class="nav-link-text">Dashboard</span></a> / Advertisement</li>
      </ol>
      <div class="row">
        <div class="col-md-12">
          <a class="btn btn-primary" href="{{ route('advertisement.create') }}" style="float: right; margin: 10px; color: #fff;">ADD</a>
        </div>
      </div>
       @if(Session::has('success'))
          <div class="alert alert-success text-center" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          {{Session('success')}}
        </div>
          @endif
          @if(Session::has('error'))
          <div class="alert alert-danger text-center" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          {{Session('error')}}
        </div>
          @endif
      <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-table"></i> Data Table Example</div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>S.No.</th>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Image</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tfoot>
                <tr>
                  <th>S.No.</th>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Image</th>
                  <th>Action</th>
                </tr>
              </tfoot>
              <tbody>
                @foreach ($advertisement as $key=>$data)
                <tr>
                   <td>{{$key+1}}</td>
                    <td>{{$data->name}}</td>
                    <td>{{$data->description}}</td>
                    
                    <td><img src="{{URL::to('public/images/advertisement/'.$data->image)}}" width="50px" class="img-responsive"></td>
                    <td class="text-center">{!! Form::open(['class'=>'delete_form','method'=>'DELETE','action' =>['advertisement\advertisementController@destroy',$data->id]]) !!}
                    <div class="form-group">
                            {{Form::button('<i class="fa fa-trash"></i>',['class'=>'delete_btn','type'=>'submit','onclick'=>'return confirm("Do you want to delete")'])}}
                    </div>
                     {!! Form::close() !!}
                        <a href="{{route('advertisement.edit', $data->id) }}"><i class="fa fa-pencil-square-o"></i></a>
                    </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
        <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
      </div>
          
    </div>
    
@endsection

resources/views/layouts/admin/pages/advertisement/editadvertisement.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item active"><a href="{{route('home')}}"><span class="nav-link-text">Dashboard</span></a> / <a href="{{route('advertisement.index')}}"><span class="nav-link-text">Advertisements</span></a> / Edit Advertisement</li>
      </ol>      
          <div class="row">
            <div class="col-lg-12">
              {!! Form::model($editadvertisement,array('route'=>['advertisement.update',$editadvertisement->id],'method'=>'PUT', 'files'=>'true'))!!}
                <div class="row p-3">
                <div class="col-lg-6">
                <div class="form-group">
                <label>advertisement Name</label>
                <input class="form-control" name="name" value="{{$editadvertisement->name}}">
                </div>
              </div>
              <div class="col-lg-12">
                <div class="form-group">
                <label>Description</label>
                <textarea name="description" class="form-control" rows="3">{{$editadvertisement->description}}</textarea>
                </div>
              </div>              
              <div class="col-lg-6">
                <div class="form-group">
                <label>advertisement Image (PNG,JPG) : </label>
                <input type="file" name="img">
                </div>
              </div>
              <div class="col-lg-12">
                <button type="submit" class="btn btn-primary">Update</button>
                <a href="{{ route('advertisement.index') }}" class="btn btn-danger">Cancel</a>
                </div>
              </div>              
              {!! Form::close() !!}
              </div>
          </div>
    </div>
  </div>
    
@endsection