routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//route for product
Route::resource('product', 'product\productController');
//route for category
Route::resource('category', 'category\categoryController');
//route for brand
Route::resource('brand', 'brand\brandController');
//route for setting
Route::resource('setting', 'setting\settingController');
//route for advertisement
Route::resource('advertisement', 'advertisement\advertisementController');

//route for password change
Route::resource('changepassword', 'Auth\adminController');

//route of order
Route::GET('Order','product\ProductController@order')->name('order');

routes/user.php
<?php
Route::get('/', 'product\frontProductController@home')->name('main');
Route::GET('login','User\LoginController@showLoginForm')->name('user.login');
Route::GET('userlogout','User\LoginController@logout')->name('user.logout');
Route::POST('login','User\LoginController@login');
/*cart list */
Route::GET('my-cart/{id}','product\frontProductController@cartView')->name('cart');
Route::GET('cartdelete/{id}','product\frontProductController@cartDelete')->name('deletecart');
Route::POST('AddCart','product\frontProductController@addToCart')->name('addcart');
/*Wish list */
Route::POST('AddWish','product\frontProductController@addToWish')->name('addwishlist');
Route::GET('my-wish/{id}','product\frontProductController@wishView')->name('wish');
Route::GET('wishdelete/{id}','product\frontProductController@wishDelete')->name('deletewish');
/*product list */
Route::GET('listproduct','product\frontProductController@showListProduct')->name('listproduct');
Route::GET('productdetail/{slug}','product\frontProductController@showProductDetail')->name('listdetail');
/*brand */
Route::GET('Brand/{slug}','product\frontProductController@showListProductByBrand')->name('brand');
/*category */
Route::GET('Category/{slug}','product\frontProductController@showListProductByCategory')->name('category');

Route::POST('Search/Product','product\frontProductController@showSearchProduct')->name('search');
Route::GET('User/Help','product\frontProductController@showHelp')->name('help');
/*social login */
Route::get('auth/{provider}', 'User\LoginController@redirectToProvider');
Route::get('auth/{provider}/callback', 'User\LoginController@handleProviderCallback');
/*Pages */
Route::GET('Contact','product\frontProductController@showContact')->name('contact');
Route::GET('About','product\frontProductController@showAbout')->name('about');
/*Profile*/
Route::GET('My-Profile','User\userController@showProfile')->name('profile');
Route::GET('My-Profile/Edit-Profile','User\userController@showProfileEdit')->name('editprofile');
Route::GET('My-Profile/Change-Password','User\userController@showpassword')->name('password');
Route::POST('changepassword/{id}','User\userController@changepassword')->name('changepassword');
Route::POST('changeprofile/{id}','User\userController@update')->name('profileedit');

Route::POST('registeruser','User\userController@userRegister')->name('userregister');
?>

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('index', 'HomeController@home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/category/categoryController.php
<?php

namespace App\Http\Controllers\category;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repo\Repository\Category\CategoryRepositoryInterface;

class categoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct(CategoryRepositoryInterface $Category)
    {
        $this->middleware('auth');
        $this->Category=$Category;

    }
    public function index()
    {
        $category=$this->Category->index();
        return view('layouts/admin/pages/category/category', compact('category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('layouts/admin/pages/category/addcategory');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
            $Categorydetails['name']=$request->name;
            $Categorydetails['slug']=str_slug($Categorydetails['name'], '-');
            $this->Category->create($Categorydetails);
            return redirect()->route('category.index')->with('success', 'Your Category has been successfully Created.');
        }
        catch(Exception $e)
        {
            dd($e);

        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->Category->find($id);
        return view('layouts/admin/pages/category/editcategory' , compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         try{
            $Categorydetails['name']=$request->name;
            $Categorydetails['slug']=str_slug($Categorydetails['name'], '-');
            $this->Category->update($id,$Categorydetails);
            return redirect()->route('category.index')->with('success', 'Your Category has been successfully Update.');
        }
        catch(Exception $e)
        {
            dd($e);

        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->Category->delete($id);
        return redirect()->route('category.index')->with('success', 'Your category has been successfully deleted.');
    
    }
}

resources/views/layouts/admin/pages/category/addcategory.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item active"><a href="{{route('home')}}"><span class="nav-link-text">Dashboard</span></a> / <a href="{{route('category.index')}}"><span class="nav-link-text">Categorys</span></a> / Add Category</li>
      </ol>      
          <div class="row">
            <div class="col-lg-12">
              <form role="form" method="post" action="{{route('category.store')}}">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <div class="row p-3">
                <div class="col-lg-6">
                <div class="form-group">
                <label>Category Name</label>
                <input class="form-control" name="name" placeholder="Enter Category Name">
                </div>
              </div>
              <div class="col-lg-12">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{{ route('category.index') }}" class="btn btn-danger">Cancel</a>
                </div>
              </div>              
              </form>
              </div>
          </div>
    </div>
  </div>
    
@endsection

resources/views/layouts/admin/pages/category/category.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item active"><a href="{{route('home')}}"><span class="nav-link-text">Dashboard</span></a> / Categorys</li>
      </ol>
      <div class="row">
        <div class="col-md-12">
          <a class="btn btn-primary" href="{{ route('category.create') }}" style="float: right; margin: 10px; color: #fff;">ADD</a>
        </div>
      </div>
       @if(Session::has('success'))
          <div class="alert alert-success text-center" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          {{Session('success')}}
        </div>
          @endif
          @if(Session::has('error'))
          <div class="alert alert-danger text-center" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          {{Session('error')}}
        </div>
          @endif
      <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-table"></i> Data Table Category</div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>S.No</th>
                  <th>Category Name</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tfoot>
                <tr>
                  <th>S.No</th>
                  <th>Category Name</th>
                  <th>Action</th>
                </tr>
              </tfoot>
              <tbody>
                @foreach($category as $key=>$data)
                <tr>
                  <td>{{$key+1}}</td>
                  <td>{{$data->name}}</td>
                  <td>{!! Form::open(['class'=>'delete_form','method'=>'DELETE','action' =>['category\categoryController@destroy',$data->id]]) !!}
                      <div class="form-group">
                              {{Form::button('<i class="fa fa-trash"></i>',['class'=>'delete_btn','type'=>'submit','onclick'=>'return confirm("Do you want to delete")'])}}
                      </div>
                       {!! Form::close() !!}
                          <a href="{{route('category.edit', $data->id) }}"><i class="fa fa-pencil-square-o"></i></a></td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
        <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
      </div>
          
    </div>
    
@endsection

resources/views/layouts/admin/pages/category/editcategory.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item active"><a href="{{route('home')}}"><span class="nav-link-text">Dashboard</span></a> / <a href="{{route('category.index')}}"><span class="nav-link-text">Categorys</span></a> / Edit Category</li>
      </ol>      
          <div class="row">
            <div class="col-lg-12">
              {!! Form::model($category,array('route'=>['category.update',$category->id],'method'=>'PUT', 'files'=>'true'))!!}
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <div class="row p-3">
                <div class="col-lg-6">
                <div class="form-group">
                <label>Category Name</label>
                <input class="form-control" name="name" value="{{$category->name}}" placeholder="Enter Category Name">
                </div>
              </div>
              <div class="col-lg-12">
                <button type="submit" class="btn btn-primary">Update</button>
                <a href="{{ route('category.index') }}" class="btn btn-danger">Cancel</a>
                </div>
              </div>              
              {!! Form::close() !!}
              </div>
          </div>
    </div>
  </div>
    
@endsection