routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//route for product
Route::resource('product', 'product\productController');
//route for category
Route::resource('category', 'category\categoryController');
//route for brand
Route::resource('brand', 'brand\brandController');
//route for setting
Route::resource('setting', 'setting\settingController');
//route for advertisement
Route::resource('advertisement', 'advertisement\advertisementController');

//route for password change
Route::resource('changepassword', 'Auth\adminController');

//route of order
Route::GET('Order','product\ProductController@order')->name('order');

routes/user.php
<?php
Route::get('/', 'product\frontProductController@home')->name('main');
Route::GET('login','User\LoginController@showLoginForm')->name('user.login');
Route::GET('userlogout','User\LoginController@logout')->name('user.logout');
Route::POST('login','User\LoginController@login');
/*cart list */
Route::GET('my-cart/{id}','product\frontProductController@cartView')->name('cart');
Route::GET('cartdelete/{id}','product\frontProductController@cartDelete')->name('deletecart');
Route::POST('AddCart','product\frontProductController@addToCart')->name('addcart');
/*Wish list */
Route::POST('AddWish','product\frontProductController@addToWish')->name('addwishlist');
Route::GET('my-wish/{id}','product\frontProductController@wishView')->name('wish');
Route::GET('wishdelete/{id}','product\frontProductController@wishDelete')->name('deletewish');
/*product list */
Route::GET('listproduct','product\frontProductController@showListProduct')->name('listproduct');
Route::GET('productdetail/{slug}','product\frontProductController@showProductDetail')->name('listdetail');
/*brand */
Route::GET('Brand/{slug}','product\frontProductController@showListProductByBrand')->name('brand');
/*category */
Route::GET('Category/{slug}','product\frontProductController@showListProductByCategory')->name('category');

Route::POST('Search/Product','product\frontProductController@showSearchProduct')->name('search');
Route::GET('User/Help','product\frontProductController@showHelp')->name('help');
/*social login */
Route::get('auth/{provider}', 'User\LoginController@redirectToProvider');
Route::get('auth/{provider}/callback', 'User\LoginController@handleProviderCallback');
/*Pages */
Route::GET('Contact','product\frontProductController@showContact')->name('contact');
Route::GET('About','product\frontProductController@showAbout')->name('about');
/*Profile*/
Route::GET('My-Profile','User\userController@showProfile')->name('profile');
Route::GET('My-Profile/Edit-Profile','User\userController@showProfileEdit')->name('editprofile');
Route::GET('My-Profile/Change-Password','User\userController@showpassword')->name('password');
Route::POST('changepassword/{id}','User\userController@changepassword')->name('changepassword');
Route::POST('changeprofile/{id}','User\userController@update')->name('profileedit');

Route::POST('registeruser','User\userController@userRegister')->name('userregister');
?>

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('index', 'HomeController@home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/layouts/admin/footer.blade.php
<footer class="sticky-footer">
      <div class="container">
        <div class="text-center">
          <small>Copyright © Your Website 2017</small>
        </div>
      </div>
    </footer>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="login.html">Logout</a>
          </div>
        </div>
      </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="{{URL::to('public/admin/vendor/jquery/jquery.min.js')}}"></script>
    <script src="{{URL::to('public/admin/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
    <!-- Core plugin JavaScript-->
    <script src="{{URL::to('public/admin/vendor/jquery-easing/jquery.easing.min.js')}}"></script>
    <!-- Page level plugin JavaScript-->
    <script src="{{URL::to('public/admin/vendor/chart.js/Chart.min.js')}}"></script>
    <script src="{{URL::to('public/admin/vendor/datatables/jquery.dataTables.js')}}"></script>
    <script src="{{URL::to('public/admin/vendor/datatables/dataTables.bootstrap4.js')}}"></script>
    <!-- Custom scripts for all pages-->
    <script src="{{URL::to('public/admin/js/sb-admin.min.js')}}"></script>
    <!-- Custom scripts for this page-->
    <script src="{{URL::to('public/admin/js/sb-admin-datatables.min.js')}}"></script>
    <script src="{{URL::to('public/admin/js/sb-admin-charts.min.js')}}"></script>
  </div>
</body>

</html>

resources/views/layouts/admin/header.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>DOKAN NEPAL ADMIN</title>
  <!-- Bootstrap core CSS-->
  <link href="{{URL::to('public/admin/vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
  <!-- Custom fonts for this template-->
  <link href="{{URL::to('public/admin/vendor/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">
  <!-- Page level plugin CSS-->
  <link href="{{URL::to('public/admin/vendor/datatables/dataTables.bootstrap4.css')}}" rel="stylesheet">
  <!-- Custom styles for this template-->
  <link href="{{URL::to('public/admin/css/sb-admin.css')}}" rel="stylesheet">
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="{{ route('home') }}">DOKAN NEPAL</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="{{ route('home') }}">
            <i class="fa fa-fw fa-dashboard"></i>
            <span class="nav-link-text">Dashboard</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Menu Levels">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-sitemap"></i>
            <span class="nav-link-text">Product</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseMulti">
            <li>
              <a href="{{ route('product.index') }}">
               <i class="fa fa-fw fa-shopping-cart"></i>
            <span class="nav-link-text">Products</span>
          </a>
            </li>
            <li>
              <a href="{{ route('order') }}">
               <i class="fa fa-shopping-bag" aria-hidden="true"></i>
            <span class="nav-link-text">Orders</span>
          </a>
            </li>
          </ul>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
          <a class="nav-link" href="{{ route('category.index') }}">
            <i class="fa fa-list"></i>
            <span class="nav-link-text">Category</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
          <a class="nav-link" href="{{ route('brand.index') }}">
            <i class="fa fa-star"></i>
            <span class="nav-link-text">Brand</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
          <a class="nav-link" href="{{ route('advertisement.index') }}">
            <i class="fa fa-address-card-o" aria-hidden="true"></i>
            <span class="nav-link-text">Advertisement</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
          <a class="nav-link" href="{{ route('setting.index') }}">
            <i class="fa fa-cogs"></i>
            <span class="nav-link-text">Site Setting</span>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item">
          <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle mr-lg-2" id="messagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-fw fa-envelope"></i>
            <span class="d-lg-none">Messages
              <span class="badge badge-pill badge-primary">12 New</span>
            </span>
            <span class="indicator text-primary d-none d-lg-block">
              <i class="fa fa-fw fa-circle"></i>
            </span>
          </a>
          <div class="dropdown-menu" aria-labelledby="messagesDropdown">
            <h6 class="dropdown-header">New Messages:</h6>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <strong>David Miller</strong>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">Hey there! This new version of SB Admin is pretty awesome! These messages clip off when they reach the end of the box so they don't overflow over to the sides!</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <strong>Jane Smith</strong>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">I was wondering if you could meet for an appointment at 3:00 instead of 4:00. Thanks!</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <strong>John Doe</strong>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">I've sent the final files over to you for review. When you're able to sign off of them let me know and we can discuss distribution.</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item small" href="#">View all messages</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{route('changepassword.index')}}">
            <i class="fa fa-fw fa-key"></i>Change Password</a>
          </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
            <i class="fa fa-fw fa-sign-out"></i>Logout</a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
        </li>
      </ul>
    </div>
  </nav>


                                       